trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /AzureMonitor/*
variables:
  serviceConnection: 'app-policy-deployment'
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Deploy
  jobs:
    - job: Deploy
      steps:
        - checkout: self
          path: POLICY
        - task: AzureCLI@2
          displayName: 'DeployAzureMonitorPolicy'
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              set -o pipefail -e
              az deployment mg create -n DeployMonitorPolicy -l westeurope -m company-MG -f $(Pipeline.Workspace)/POLICY/AzureMonitor/main.bicep -p $(Pipeline.Workspace)/POLICY/AzureMonitor/params-prod.json
              az policy state trigger-scan --no-wait
              set +o pipefail +e
          enabled: true